//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RsDesigner
{
    using System;
    using System.Collections.Generic;
    
    public partial class DownloadRecords
    {
        public int id { get; set; }
        public int ReferenceShareRecordId { get; set; }
        public string IpAddress { get; set; }
        public string UserId { get; set; }
        public int CreatedUTC { get; set; }
        public string CreatedBy { get; set; }
    
        public virtual ReferenceShareRecords ReferenceShareRecords { get; set; }
    }
}
