//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RsDesigner
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pages
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Title { get; set; }
        public int TemplateId { get; set; }
        public string MetaTag { get; set; }
        public string MetaDescription { get; set; }
        public int CreatedUTC { get; set; }
        public int ModifiedUTC { get; set; }
        public string CreatedBy { get; set; }
        public string ModifiedBy { get; set; }
        public string Content { get; set; }
        public bool Published { get; set; }
        public System.DateTime ModifiedDateTime { get; set; }
    }
}
