//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RsDesigner
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentRecords
    {
        public PaymentRecords()
        {
            this.UserSubscriptions = new HashSet<UserSubscriptions>();
        }
    
        public int Id { get; set; }
        public string token { get; set; }
        public string PayerId { get; set; }
        public string shippingAddress { get; set; }
        public string amount { get; set; }
        public int CreatedUTC { get; set; }
        public string CreatedBy { get; set; }
        public int ModifiedUTC { get; set; }
        public string ModifiedBy { get; set; }
        public int PlanId { get; set; }
        public string Status { get; set; }
        public string TransId { get; set; }
        public string PNRef { get; set; }
        public string Action { get; set; }
        public string TransFee { get; set; }
        public string TaxAmount { get; set; }
        public bool Completed { get; set; }
        public string Message { get; set; }
    
        public virtual ICollection<UserSubscriptions> UserSubscriptions { get; set; }
    }
}
