//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RsDesigner
{
    using System;
    using System.Collections.Generic;
    
    public partial class Questions
    {
        public Questions()
        {
            this.QuestionOptions = new HashSet<QuestionOptions>();
        }
    
        public int Id { get; set; }
        public int FormId { get; set; }
        public int Type { get; set; }
        public int Order { get; set; }
        public int Group { get; set; }
        public string Text { get; set; }
        public int CreatedUTC { get; set; }
        public string CreatedBy { get; set; }
        public int ModifiedUTC { get; set; }
        public string ModifiedBy { get; set; }
    
        public virtual ICollection<QuestionOptions> QuestionOptions { get; set; }
        public virtual RefForms RefForms { get; set; }
    }
}
