//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RsDesigner
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReferenceShareRecords
    {
        public ReferenceShareRecords()
        {
            this.DownloadRecords = new HashSet<DownloadRecords>();
        }
    
        public int id { get; set; }
        public int ReferenceId { get; set; }
        public string LinkToken { get; set; }
        public int SchoolID { get; set; }
        public int ClickCount { get; set; }
        public int CreatedUTC { get; set; }
        public string CreatedBy { get; set; }
        public int ModifiedUTC { get; set; }
        public string ModifiedBy { get; set; }
    
        public virtual ICollection<DownloadRecords> DownloadRecords { get; set; }
        public virtual References References { get; set; }
    }
}
