//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RsDesigner
{
    using System;
    using System.Collections.Generic;
    
    public partial class References
    {
        public References()
        {
            this.ReferenceAnswers = new HashSet<ReferenceAnswers>();
            this.ReferenceFiles = new HashSet<ReferenceFiles>();
            this.ReferenceShareRecords = new HashSet<ReferenceShareRecords>();
        }
    
        public int id { get; set; }
        public string RefEmail { get; set; }
        public string RefUserId { get; set; }
        public string CourseID { get; set; }
        public string Note { get; set; }
        public int Status { get; set; }
        public int CreatedUTC { get; set; }
        public string CreatedBy { get; set; }
        public int ModifiedUTC { get; set; }
        public string ModifiedBy { get; set; }
        public string TransId { get; set; }
        public string Token { get; set; }
        public bool IsActive { get; set; }
        public string UserId { get; set; }
        public int ExpiryDateUTC { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual ICollection<ReferenceAnswers> ReferenceAnswers { get; set; }
        public virtual ICollection<ReferenceFiles> ReferenceFiles { get; set; }
        public virtual ICollection<ReferenceShareRecords> ReferenceShareRecords { get; set; }
    }
}
