//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RsDesigner
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserSubscriptions
    {
        public string UserId { get; set; }
        public int subscriptionPlanId { get; set; }
        public int PaymentRecordId { get; set; }
        public int ExpiryUTC { get; set; }
        public int CreatedUTC { get; set; }
        public string CreatedBy { get; set; }
        public int ModifiedUTC { get; set; }
        public string ModifiedBy { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual PaymentRecords PaymentRecords { get; set; }
        public virtual SubscriptionPlans SubscriptionPlans { get; set; }
    }
}
