//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RsDesigner
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserProfiles
    {
        public string UserId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public int Gender { get; set; }
        public string Contact { get; set; }
        public string AltContact { get; set; }
        public Nullable<int> UniversityID { get; set; }
        public Nullable<int> SchoolID { get; set; }
        public string SchoolName { get; set; }
        public string InstitutionId { get; set; }
        public bool AgreeToTerms { get; set; }
        public int CreatedUTC { get; set; }
        public string CreatedBy { get; set; }
        public int ModifiedUTC { get; set; }
        public string ModifiedBy { get; set; }
        public int Status { get; set; }
        public string InstitutionName { get; set; }
        public string Position { get; set; }
        public int RefereeType { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
    }
}
