// <auto-generated />
namespace ReferencingSystem.Model.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class Reference1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Reference1));
        
        string IMigrationMetadata.Id
        {
            get { return "201410052245157_Reference.1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
