// <auto-generated />
namespace ReferencingSystem.Model.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class Foundation : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Foundation));
        
        string IMigrationMetadata.Id
        {
            get { return "201409300408138_Foundation"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
